### Registrando un nuevo usario
POST http://127.0.0.1:3000/auth/signup
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "erick123",
  "password2": "erick123",
  "name": "Erick"
}

### Iniciar sesión
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "erick123"
}

### Salir sesión
DELETE http://127.0.0.1:3000/auth/logout
Content-Type: application/json

### Test
GET http://127.0.0.1:3000/auth/test
Content-Type: application/json