### Registrar un nuevo juego
POST http://127.0.0.1:3000/games/registerGame
Content-Type: application/json

{ 
  "tournamentPlayingCategoryId": 4,
  "firstRegistrationId": 11,
  "secondRegistrationId": 12,
  "round": 2,
  "winnerRegistrationId": 12,
  "numberOfSetsPlayed": 3,
  "setsPlayer1": [5,4,0],
  "setsPlayer2": [7,6,0]
}

### Obtener detalles de un juego en base al torneo
GET http://127.0.0.1:3000/games/getGames/4;

