### Registrar un nuevo torneo
POST http://127.0.0.1:3000/tournaments/createTournament
Content-Type: application/json

{
  "tournamentName": "Valle real 2021" , 
  "location": "Valle real", 
  "startDate":"2021-10-25", 
  "endDate": "2021-11-25", 
  "numberOfRounds": 10, 
  "tournamentTypeId": 5, 
  "surfaceTypeId": 4,
  "playingCategoryId": 1, 
  "tournamentPhoto": "https://i2.wp.com/matchtenis.com/wp-content/uploads/2019/04/Cesped-2.jpg?resize=660%2C330&ssl=1"
}


### Obtener todos los torneos
GET http://127.0.0.1:3000/tournaments/allTournaments

### Registrar un nuevo jugador en el torneo
POST http://127.0.0.1:3000/tournaments/registerPlayer
Content-Type: application/json

{
  "playerId": 1, 
  "tournamentPlayingCategoryId": 5, 
  "seed": 4
}
